const schema = `[
  {
    data: [
      {
        id: 1,
        game_id: "0022400309",
        team_id: 1610612748,
        team_abbreviation: "MIA",
        team_city: "Miami",
        player_id: 202710,
        player_name: "Jimmy Butler",
        start_position: "F",
        comment: "",
        minutes: "34:25",
        pts: 17,
        contested_shots: 2,
        contested_shots_2pt: 2,
        contested_shots_3pt: 0,
        deflections: 3,
        charges_drawn: 0,
        screen_assists: 1,
        screen_ast_pts: 2,
        off_loose_balls_recovered: 0,
        def_loose_balls_recovered: 0,
        loose_balls_recovered: 0,
        off_boxouts: 0,
        def_boxouts: 3,
        box_out_player_team_rebs: 3,
        box_out_player_rebs: 1,
        box_outs: 3,
        created_at: "2025-01-13T23:21:25.750Z",
        table_name: "player_hustle_stats",
      },
      {
        id: 17080,
        season_id: "22024",
        player_id: 1628371,
        game_id: "0022400652",
        game_date: "2025-01-27T05:00:00.000Z",
        matchup: "ORL @ MIA",
        wl: "L",
        min: 18,
        fgm: 5,
        fga: 9,
        fg_pct: "0.556",
        fg3m: 0,
        fg3a: 2,
        fg3_pct: "0.000",
        ftm: 2,
        fta: 4,
        ft_pct: "0.500",
        oreb: 5,
        dreb: 3,
        reb: 8,
        ast: 0,
        stl: 1,
        blk: 0,
        tov: 0,
        pf: 2,
        pts: 12,
        plus_minus: 2,
        video_available: 1,
        created_at: "2025-01-28T23:30:58.155Z",
        table_name: "player_performances",
      },
      {
        id: "1",
        game_id: "0022400080",
        game_event_id: 7,
        player_id: 1630596,
        player_name: "Evan Mobley",
        team_id: 1610612739,
        team_name: "Cleveland Cavaliers",
        period: 1,
        minutes_remaining: 11,
        seconds_remaining: 39,
        game_date: "2024-10-25T04:00:00.000Z",
        event_type: "Missed Shot",
        action_type: "Layup Shot",
        shot_type: "2PT Field Goal",
        shot_zone_basic: "In The Paint (Non-RA)",
        shot_zone_area: "Center(C)",
        shot_zone_range: "Less Than 8 ft.",
        shot_distance: 7,
        loc_x: 32,
        loc_y: 63,
        shot_attempted_flag: 1,
        shot_made_flag: 0,
        htm: "CLE",
        vtm: "DET",
        created_at: "2025-01-13T18:49:04.297Z",
        table_name: "player_shot_chart_detail",
      },
      {
        id: 1,
        game_id: "0022400001",
        player_id: 1627759,
        minutes: "35:56",
        speed: "4.14",
        distance: "2.65",
        rebound_chances_offensive: 5,
        rebound_chances_defensive: 7,
        rebound_chances_total: 11,
        touches: 60,
        secondary_assists: 2,
        free_throw_assists: 0,
        passes: 26,
        assists: 2,
        contested_fg_made: 4,
        contested_fg_attempted: 7,
        contested_fg_pct: "0.571",
        uncontested_fg_made: 10,
        uncontested_fg_attempted: 15,
        uncontested_fg_pct: "0.667",
        fg_pct: "0.636",
        defended_at_rim_fg_made: 4,
        defended_at_rim_fg_attempted: 7,
        defended_at_rim_fg_pct: "0.571",
        created_at: "2025-01-13T04:44:51.091Z",
        table_name: "player_tracking_stats",
      },
      {
        id: 1631157,
        full_name: "Ryan Rollins",
        first_name: "Ryan",
        last_name: "Rollins",
        is_active: true,
        team_id: 1610612749,
        height: "6-3",
        weight: "180",
        season_exp: 2,
        jersey: "13",
        position: "Guard",
        rosterstatus: "Active",
        games_played_current_season_id: "Y",
        games_played_current_season: null,
        draft_year: "2022",
        draft_round: "2",
        draft_number: "44",
        greatest_75_flag: false,
        from_year: 2022,
        to_year: 2024,
        college: "Toledo",
        country: "USA",
        birthdate: "2002-07-03T04:00:00.000Z",
        birth_city: null,
        birth_state: null,
        birth_country: null,
        team_name: "Bucks",
        team_abbreviation: "MIL",
        team_city: "Milwaukee",
        player_code: "ryan_rollins",
        created_at: "2025-01-13T02:55:11.121Z",
        updated_at: "2025-01-13T02:55:11.121Z",
        headshot_url:
          "https://cgwnerjyklbkcwptzxpq.supabase.co/storage/v1/object/public/images/1631157_8cb5395044774223a7bb06c01e8ea2b3.png?",
        table_name: "players",
      },
      {
        id: 1,
        game_id: "0022400436",
        team_id: 1610612751,
        team_name: "Nets",
        team_abbreviation: "BKN",
        team_city: "Brooklyn",
        minutes: "240.000000:00",
        pts: 101,
        contested_shots: 32,
        contested_shots_2pt: 16,
        contested_shots_3pt: 16,
        deflections: 19,
        charges_drawn: 1,
        screen_assists: 12,
        screen_ast_pts: 27,
        off_loose_balls_recovered: 1,
        def_loose_balls_recovered: 2,
        loose_balls_recovered: 3,
        off_boxouts: 0,
        def_boxouts: 4,
        box_out_player_team_rebs: 4,
        box_out_player_rebs: 1,
        box_outs: 4,
        created_at: "2025-01-13T23:22:31.969Z",
        table_name: "team_hustle_stats",
      },
      {
        id: 1610612760,
        full_name: "Oklahoma City Thunder",
        abbreviation: "OKC",
        nickname: "Thunder",
        city: "Oklahoma City",
        state: "Oklahoma",
        year_founded: 1967,
        table_name: "teams",
      },
      {
        id: "fdc8f779-409c-40aa-9da4-7f4bad02d226",
        user_id: "01cfd8de-47e9-4748-b561-86feef6159bd",
        prompt: "who won  pritchard award? farthest shot made this past week",
        success: true,
        query:
          "SELECT p.*, psc.*, pp.*, pts.* FROM players p JOIN player_shot_chart_detail psc ON p.id = psc.player_id JOIN player_performances pp ON p.id = pp.player_id AND psc.game_id = pp.game_id JOIN player_tracking_stats pts ON pp.player_id = pts.player_id AND pp.game_id = pts.game_id WHERE psc.game_date >= '2025-01-19' AND psc.game_date <= '2025-01-25' AND psc.shot_made_flag = 1 ORDER BY psc.shot_distance DESC LIMIT 1",
        created_at: "2025-01-26T19:54:14.658Z",
        custom_summary:
          "**Nikola Jokić** won the Pritchard Award with a **66-foot shot** made this past week.",
        table_name: "user_prompts",
      },
      {
        id: "c5c7e838-93b8-4bce-be93-db067c82e6d6",
        email: "huls.chet@gmail.com",
        profile_image_url: null,
        created_at: "2025-01-16T18:55:05.979Z",
        updated_at: "2025-01-16T18:55:05.979Z",
        first_name: null,
        last_name: null,
        username: null,
        table_name: "users",
      },
    ],
  },
  {
    data: [
      {
        table_name: "player_hustle_stats",
        columns: [
          {
            column_name: "id",
            data_type: "integer",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
            constraints: [
              {
                type: "PRIMARY KEY",
                name: "player_hustle_stats_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_hustle_stats_pkey",
              },
            ],
          },
          {
            column_name: "game_id",
            data_type: "character varying",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
            constraints: [
              {
                type: "UNIQUE",
                name: "unique_player_game_hustle",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game_hustle",
              },
            ],
          },
          {
            column_name: "team_id",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "team_abbreviation",
            data_type: "text",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
          },
          {
            column_name: "team_city",
            data_type: "text",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "player_id",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
            constraints: [
              {
                type: "UNIQUE",
                name: "unique_player_game_hustle",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game_hustle",
              },
            ],
          },
          {
            column_name: "player_name",
            data_type: "text",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "start_position",
            data_type: "text",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "comment",
            data_type: "text",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "minutes",
            data_type: "text",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "pts",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "contested_shots",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "contested_shots_2pt",
            data_type: "integer",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
          },
          {
            column_name: "contested_shots_3pt",
            data_type: "integer",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
          },
          {
            column_name: "deflections",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "charges_drawn",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "screen_assists",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "screen_ast_pts",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "off_loose_balls_recovered",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "def_loose_balls_recovered",
            data_type: "integer",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
          },
          {
            column_name: "loose_balls_recovered",
            data_type: "integer",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
          },
          {
            column_name: "off_boxouts",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "def_boxouts",
            data_type: "integer",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
          },
          {
            column_name: "box_out_player_team_rebs",
            data_type: "integer",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
          },
          {
            column_name: "box_out_player_rebs",
            data_type: "integer",
            indexes: ["player_hustle_stats_pkey", "unique_player_game_hustle"],
          },
          {
            column_name: "box_outs",
            data_type: "integer",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            indexes: ["unique_player_game_hustle", "player_hustle_stats_pkey"],
          },
        ],
        indexes: [
          {
            name: "player_hustle_stats_pkey",
            columns: [
              "id",
              "game_id",
              "team_id",
              "team_abbreviation",
              "team_city",
              "player_id",
              "player_name",
              "start_position",
              "comment",
              "minutes",
              "pts",
              "contested_shots",
              "contested_shots_2pt",
              "contested_shots_3pt",
              "deflections",
              "charges_drawn",
              "screen_assists",
              "screen_ast_pts",
              "off_loose_balls_recovered",
              "def_loose_balls_recovered",
              "loose_balls_recovered",
              "off_boxouts",
              "def_boxouts",
              "box_out_player_team_rebs",
              "box_out_player_rebs",
              "box_outs",
              "created_at",
            ],
          },
          {
            name: "unique_player_game_hustle",
            columns: [
              "id",
              "game_id",
              "team_id",
              "team_abbreviation",
              "team_city",
              "player_id",
              "player_name",
              "start_position",
              "comment",
              "minutes",
              "pts",
              "contested_shots",
              "contested_shots_2pt",
              "contested_shots_3pt",
              "deflections",
              "charges_drawn",
              "screen_assists",
              "screen_ast_pts",
              "off_loose_balls_recovered",
              "def_loose_balls_recovered",
              "loose_balls_recovered",
              "off_boxouts",
              "def_boxouts",
              "box_out_player_team_rebs",
              "box_out_player_rebs",
              "box_outs",
              "created_at",
            ],
          },
        ],
      },
      {
        table_name: "player_performances",
        columns: [
          {
            column_name: "id",
            data_type: "integer",
            indexes: ["unique_player_game", "player_performances_pkey"],
            constraints: [
              {
                type: "PRIMARY KEY",
                name: "player_performances_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_performances_pkey",
              },
            ],
          },
          {
            column_name: "season_id",
            data_type: "character varying",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "player_id",
            data_type: "integer",
            indexes: ["unique_player_game", "player_performances_pkey"],
            constraints: [
              {
                type: "UNIQUE",
                name: "unique_player_game",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game",
              },
            ],
          },
          {
            column_name: "game_id",
            data_type: "character varying",
            indexes: ["unique_player_game", "player_performances_pkey"],
            constraints: [
              {
                type: "UNIQUE",
                name: "unique_player_game",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game",
              },
            ],
          },
          {
            column_name: "game_date",
            data_type: "date",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "matchup",
            data_type: "character varying",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "wl",
            data_type: "character varying",
            indexes: ["unique_player_game", "player_performances_pkey"],
          },
          {
            column_name: "min",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "fgm",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "fga",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "fg_pct",
            data_type: "numeric",
            indexes: ["unique_player_game", "player_performances_pkey"],
          },
          {
            column_name: "fg3m",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "fg3a",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "fg3_pct",
            data_type: "numeric",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "ftm",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "fta",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "ft_pct",
            data_type: "numeric",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "oreb",
            data_type: "integer",
            indexes: ["unique_player_game", "player_performances_pkey"],
          },
          {
            column_name: "dreb",
            data_type: "integer",
            indexes: ["unique_player_game", "player_performances_pkey"],
          },
          {
            column_name: "reb",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "ast",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "stl",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "blk",
            data_type: "integer",
            indexes: ["unique_player_game", "player_performances_pkey"],
          },
          {
            column_name: "tov",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "pf",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "pts",
            data_type: "integer",
            indexes: ["unique_player_game", "player_performances_pkey"],
          },
          {
            column_name: "plus_minus",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "video_available",
            data_type: "integer",
            indexes: ["player_performances_pkey", "unique_player_game"],
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            indexes: ["unique_player_game", "player_performances_pkey"],
          },
        ],
        indexes: [
          {
            name: "unique_player_game",
            columns: [
              "id",
              "season_id",
              "player_id",
              "game_id",
              "game_date",
              "matchup",
              "wl",
              "min",
              "fgm",
              "fga",
              "fg_pct",
              "fg3m",
              "fg3a",
              "fg3_pct",
              "ftm",
              "fta",
              "ft_pct",
              "oreb",
              "dreb",
              "reb",
              "ast",
              "stl",
              "blk",
              "tov",
              "pf",
              "pts",
              "plus_minus",
              "video_available",
              "created_at",
            ],
          },
          {
            name: "player_performances_pkey",
            columns: [
              "id",
              "season_id",
              "player_id",
              "game_id",
              "game_date",
              "matchup",
              "wl",
              "min",
              "fgm",
              "fga",
              "fg_pct",
              "fg3m",
              "fg3a",
              "fg3_pct",
              "ftm",
              "fta",
              "ft_pct",
              "oreb",
              "dreb",
              "reb",
              "ast",
              "stl",
              "blk",
              "tov",
              "pf",
              "pts",
              "plus_minus",
              "video_available",
              "created_at",
            ],
          },
        ],
      },
      {
        table_name: "player_shot_chart_detail",
        columns: [
          {
            column_name: "id",
            data_type: "bigint",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
            constraints: [
              {
                type: "PRIMARY KEY",
                name: "player_shot_chart_detail_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_shot_chart_detail_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_shot_chart_detail_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_shot_chart_detail_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_shot_chart_detail_pkey",
              },
            ],
          },
          {
            column_name: "game_id",
            data_type: "text",
            indexes: [
              "idx_player_shot_chart_game_date",
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_player_id",
            ],
            constraints: [
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
            ],
          },
          {
            column_name: "game_event_id",
            data_type: "integer",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
            constraints: [
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
              {
                type: "UNIQUE",
                name: "player_shot_chart_detail_game_id_game_event_id_key",
              },
            ],
          },
          {
            column_name: "player_id",
            data_type: "integer",
            indexes: [
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_player_id",
            ],
          },
          {
            column_name: "player_name",
            data_type: "text",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
          },
          {
            column_name: "team_id",
            data_type: "integer",
            indexes: [
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
            ],
          },
          {
            column_name: "team_name",
            data_type: "text",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
          },
          {
            column_name: "period",
            data_type: "integer",
            indexes: [
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_player_id",
            ],
          },
          {
            column_name: "minutes_remaining",
            data_type: "integer",
            indexes: [
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
            ],
          },
          {
            column_name: "seconds_remaining",
            data_type: "integer",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
          },
          {
            column_name: "game_date",
            data_type: "date",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
          },
          {
            column_name: "event_type",
            data_type: "text",
            indexes: [
              "player_shot_chart_detail_pkey",
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
            ],
          },
          {
            column_name: "action_type",
            data_type: "text",
            indexes: [
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_player_id",
            ],
          },
          {
            column_name: "shot_type",
            data_type: "text",
            indexes: [
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_game_date",
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_player_id",
            ],
          },
          {
            column_name: "shot_zone_basic",
            data_type: "text",
            indexes: [
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_pkey",
            ],
          },
          {
            column_name: "shot_zone_area",
            data_type: "text",
            indexes: [
              "idx_player_shot_chart_player_id",
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_game_date",
            ],
          },
          {
            column_name: "shot_zone_range",
            data_type: "text",
            indexes: [
              "player_shot_chart_detail_pkey",
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
            ],
          },
          {
            column_name: "shot_distance",
            data_type: "integer",
            indexes: [
              "idx_player_shot_chart_player_id",
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_game_date",
            ],
          },
          {
            column_name: "loc_x",
            data_type: "integer",
            indexes: [
              "player_shot_chart_detail_pkey",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_player_id",
            ],
          },
          {
            column_name: "loc_y",
            data_type: "integer",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
          },
          {
            column_name: "shot_attempted_flag",
            data_type: "integer",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
          },
          {
            column_name: "shot_made_flag",
            data_type: "integer",
            indexes: [
              "idx_player_shot_chart_player_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_game_id",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "player_shot_chart_detail_pkey",
            ],
          },
          {
            column_name: "htm",
            data_type: "text",
            indexes: [
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_player_id",
            ],
          },
          {
            column_name: "vtm",
            data_type: "text",
            indexes: [
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_player_id",
              "player_shot_chart_detail_pkey",
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
            ],
          },
          {
            column_name: "created_at",
            data_type: "timestamp with time zone",
            indexes: [
              "player_shot_chart_detail_game_id_game_event_id_key",
              "idx_player_shot_chart_game_id",
              "idx_player_shot_chart_game_date",
              "idx_player_shot_chart_player_id",
              "player_shot_chart_detail_pkey",
            ],
          },
        ],
        indexes: [
          {
            name: "idx_player_shot_chart_player_id",
            columns: [
              "id",
              "game_id",
              "game_event_id",
              "player_id",
              "player_name",
              "team_id",
              "team_name",
              "period",
              "minutes_remaining",
              "seconds_remaining",
              "game_date",
              "event_type",
              "action_type",
              "shot_type",
              "shot_zone_basic",
              "shot_zone_area",
              "shot_zone_range",
              "shot_distance",
              "loc_x",
              "loc_y",
              "shot_attempted_flag",
              "shot_made_flag",
              "htm",
              "vtm",
              "created_at",
            ],
          },
          {
            name: "idx_player_shot_chart_game_date",
            columns: [
              "id",
              "game_id",
              "game_event_id",
              "player_id",
              "player_name",
              "team_id",
              "team_name",
              "period",
              "minutes_remaining",
              "seconds_remaining",
              "game_date",
              "event_type",
              "action_type",
              "shot_type",
              "shot_zone_basic",
              "shot_zone_area",
              "shot_zone_range",
              "shot_distance",
              "loc_x",
              "loc_y",
              "shot_attempted_flag",
              "shot_made_flag",
              "htm",
              "vtm",
              "created_at",
            ],
          },
          {
            name: "idx_player_shot_chart_game_id",
            columns: [
              "id",
              "game_id",
              "game_event_id",
              "player_id",
              "player_name",
              "team_id",
              "team_name",
              "period",
              "minutes_remaining",
              "seconds_remaining",
              "game_date",
              "event_type",
              "action_type",
              "shot_type",
              "shot_zone_basic",
              "shot_zone_area",
              "shot_zone_range",
              "shot_distance",
              "loc_x",
              "loc_y",
              "shot_attempted_flag",
              "shot_made_flag",
              "htm",
              "vtm",
              "created_at",
            ],
          },
          {
            name: "player_shot_chart_detail_game_id_game_event_id_key",
            columns: [
              "id",
              "game_id",
              "game_event_id",
              "player_id",
              "player_name",
              "team_id",
              "team_name",
              "period",
              "minutes_remaining",
              "seconds_remaining",
              "game_date",
              "event_type",
              "action_type",
              "shot_type",
              "shot_zone_basic",
              "shot_zone_area",
              "shot_zone_range",
              "shot_distance",
              "loc_x",
              "loc_y",
              "shot_attempted_flag",
              "shot_made_flag",
              "htm",
              "vtm",
              "created_at",
            ],
          },
          {
            name: "player_shot_chart_detail_pkey",
            columns: [
              "id",
              "game_id",
              "game_event_id",
              "player_id",
              "player_name",
              "team_id",
              "team_name",
              "period",
              "minutes_remaining",
              "seconds_remaining",
              "game_date",
              "event_type",
              "action_type",
              "shot_type",
              "shot_zone_basic",
              "shot_zone_area",
              "shot_zone_range",
              "shot_distance",
              "loc_x",
              "loc_y",
              "shot_attempted_flag",
              "shot_made_flag",
              "htm",
              "vtm",
              "created_at",
            ],
          },
        ],
      },
      {
        table_name: "player_tracking_stats",
        columns: [
          {
            column_name: "id",
            data_type: "integer",
            indexes: [
              "player_tracking_stats_pkey",
              "idx_tracking_player_id",
              "unique_player_game_tracking",
              "idx_tracking_game_id",
            ],
            constraints: [
              {
                type: "PRIMARY KEY",
                name: "player_tracking_stats_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_tracking_stats_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_tracking_stats_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "player_tracking_stats_pkey",
              },
            ],
          },
          {
            column_name: "game_id",
            data_type: "character varying",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_game_id",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
            ],
            constraints: [
              {
                type: "UNIQUE",
                name: "unique_player_game_tracking",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game_tracking",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game_tracking",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game_tracking",
              },
            ],
          },
          {
            column_name: "player_id",
            data_type: "integer",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_game_id",
              "player_tracking_stats_pkey",
              "idx_tracking_player_id",
            ],
            constraints: [
              {
                type: "UNIQUE",
                name: "unique_player_game_tracking",
                foreign_table: "players",
                foreign_column: "id",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game_tracking",
                foreign_table: "players",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "player_tracking_stats_player_id_fkey",
                foreign_table: "players",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "player_tracking_stats_player_id_fkey",
                foreign_table: "players",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "player_tracking_stats_player_id_fkey",
                foreign_table: "players",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "player_tracking_stats_player_id_fkey",
                foreign_table: "players",
                foreign_column: "id",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game_tracking",
                foreign_table: "players",
                foreign_column: "id",
              },
              {
                type: "UNIQUE",
                name: "unique_player_game_tracking",
                foreign_table: "players",
                foreign_column: "id",
              },
            ],
          },
          {
            column_name: "minutes",
            data_type: "character varying",
            indexes: [
              "unique_player_game_tracking",
              "player_tracking_stats_pkey",
              "idx_tracking_game_id",
              "idx_tracking_player_id",
            ],
          },
          {
            column_name: "speed",
            data_type: "numeric",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_game_id",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "distance",
            data_type: "numeric",
            indexes: [
              "idx_tracking_game_id",
              "unique_player_game_tracking",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "rebound_chances_offensive",
            data_type: "integer",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_game_id",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "rebound_chances_defensive",
            data_type: "integer",
            indexes: [
              "player_tracking_stats_pkey",
              "idx_tracking_game_id",
              "idx_tracking_player_id",
              "unique_player_game_tracking",
            ],
          },
          {
            column_name: "rebound_chances_total",
            data_type: "integer",
            indexes: [
              "player_tracking_stats_pkey",
              "idx_tracking_game_id",
              "idx_tracking_player_id",
              "unique_player_game_tracking",
            ],
          },
          {
            column_name: "touches",
            data_type: "integer",
            indexes: [
              "player_tracking_stats_pkey",
              "idx_tracking_game_id",
              "unique_player_game_tracking",
              "idx_tracking_player_id",
            ],
          },
          {
            column_name: "secondary_assists",
            data_type: "integer",
            indexes: [
              "idx_tracking_player_id",
              "idx_tracking_game_id",
              "unique_player_game_tracking",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "free_throw_assists",
            data_type: "integer",
            indexes: [
              "player_tracking_stats_pkey",
              "idx_tracking_game_id",
              "unique_player_game_tracking",
              "idx_tracking_player_id",
            ],
          },
          {
            column_name: "passes",
            data_type: "integer",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_player_id",
              "idx_tracking_game_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "assists",
            data_type: "integer",
            indexes: [
              "player_tracking_stats_pkey",
              "idx_tracking_player_id",
              "idx_tracking_game_id",
              "unique_player_game_tracking",
            ],
          },
          {
            column_name: "contested_fg_made",
            data_type: "integer",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_player_id",
              "idx_tracking_game_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "contested_fg_attempted",
            data_type: "integer",
            indexes: [
              "idx_tracking_game_id",
              "unique_player_game_tracking",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "contested_fg_pct",
            data_type: "numeric",
            indexes: [
              "idx_tracking_player_id",
              "unique_player_game_tracking",
              "idx_tracking_game_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "uncontested_fg_made",
            data_type: "integer",
            indexes: [
              "idx_tracking_game_id",
              "unique_player_game_tracking",
              "player_tracking_stats_pkey",
              "idx_tracking_player_id",
            ],
          },
          {
            column_name: "uncontested_fg_attempted",
            data_type: "integer",
            indexes: [
              "idx_tracking_game_id",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
              "unique_player_game_tracking",
            ],
          },
          {
            column_name: "uncontested_fg_pct",
            data_type: "numeric",
            indexes: [
              "idx_tracking_game_id",
              "unique_player_game_tracking",
              "player_tracking_stats_pkey",
              "idx_tracking_player_id",
            ],
          },
          {
            column_name: "fg_pct",
            data_type: "numeric",
            indexes: [
              "idx_tracking_game_id",
              "player_tracking_stats_pkey",
              "idx_tracking_player_id",
              "unique_player_game_tracking",
            ],
          },
          {
            column_name: "defended_at_rim_fg_made",
            data_type: "integer",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_game_id",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "defended_at_rim_fg_attempted",
            data_type: "integer",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_game_id",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
            ],
          },
          {
            column_name: "defended_at_rim_fg_pct",
            data_type: "numeric",
            indexes: [
              "unique_player_game_tracking",
              "idx_tracking_player_id",
              "player_tracking_stats_pkey",
              "idx_tracking_game_id",
            ],
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            indexes: [
              "player_tracking_stats_pkey",
              "unique_player_game_tracking",
              "idx_tracking_player_id",
              "idx_tracking_game_id",
            ],
          },
        ],
        indexes: [
          {
            name: "player_tracking_stats_pkey",
            columns: [
              "id",
              "game_id",
              "player_id",
              "minutes",
              "speed",
              "distance",
              "rebound_chances_offensive",
              "rebound_chances_defensive",
              "rebound_chances_total",
              "touches",
              "secondary_assists",
              "free_throw_assists",
              "passes",
              "assists",
              "contested_fg_made",
              "contested_fg_attempted",
              "contested_fg_pct",
              "uncontested_fg_made",
              "uncontested_fg_attempted",
              "uncontested_fg_pct",
              "fg_pct",
              "defended_at_rim_fg_made",
              "defended_at_rim_fg_attempted",
              "defended_at_rim_fg_pct",
              "created_at",
            ],
          },
          {
            name: "idx_tracking_player_id",
            columns: [
              "id",
              "game_id",
              "player_id",
              "minutes",
              "speed",
              "distance",
              "rebound_chances_offensive",
              "rebound_chances_defensive",
              "rebound_chances_total",
              "touches",
              "secondary_assists",
              "free_throw_assists",
              "passes",
              "assists",
              "contested_fg_made",
              "contested_fg_attempted",
              "contested_fg_pct",
              "uncontested_fg_made",
              "uncontested_fg_attempted",
              "uncontested_fg_pct",
              "fg_pct",
              "defended_at_rim_fg_made",
              "defended_at_rim_fg_attempted",
              "defended_at_rim_fg_pct",
              "created_at",
            ],
          },
          {
            name: "unique_player_game_tracking",
            columns: [
              "id",
              "game_id",
              "player_id",
              "minutes",
              "speed",
              "distance",
              "rebound_chances_offensive",
              "rebound_chances_defensive",
              "rebound_chances_total",
              "touches",
              "secondary_assists",
              "free_throw_assists",
              "passes",
              "assists",
              "contested_fg_made",
              "contested_fg_attempted",
              "contested_fg_pct",
              "uncontested_fg_made",
              "uncontested_fg_attempted",
              "uncontested_fg_pct",
              "fg_pct",
              "defended_at_rim_fg_made",
              "defended_at_rim_fg_attempted",
              "defended_at_rim_fg_pct",
              "created_at",
            ],
          },
          {
            name: "idx_tracking_game_id",
            columns: [
              "id",
              "game_id",
              "player_id",
              "minutes",
              "speed",
              "distance",
              "rebound_chances_offensive",
              "rebound_chances_defensive",
              "rebound_chances_total",
              "touches",
              "secondary_assists",
              "free_throw_assists",
              "passes",
              "assists",
              "contested_fg_made",
              "contested_fg_attempted",
              "contested_fg_pct",
              "uncontested_fg_made",
              "uncontested_fg_attempted",
              "uncontested_fg_pct",
              "fg_pct",
              "defended_at_rim_fg_made",
              "defended_at_rim_fg_attempted",
              "defended_at_rim_fg_pct",
              "created_at",
            ],
          },
        ],
      },
      {
        table_name: "players",
        columns: [
          {
            column_name: "id",
            data_type: "integer",
            indexes: ["players_pkey"],
            constraints: [
              {
                type: "PRIMARY KEY",
                name: "players_pkey",
              },
            ],
          },
          {
            column_name: "full_name",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "first_name",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "last_name",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "is_active",
            data_type: "boolean",
            indexes: ["players_pkey"],
          },
          {
            column_name: "team_id",
            data_type: "integer",
            indexes: ["players_pkey"],
            constraints: [
              {
                type: "FOREIGN KEY",
                name: "players_team_id_fkey",
                foreign_table: "teams",
                foreign_column: "id",
              },
            ],
          },
          {
            column_name: "height",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "weight",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "season_exp",
            data_type: "integer",
            indexes: ["players_pkey"],
          },
          {
            column_name: "jersey",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "position",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "rosterstatus",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "games_played_current_season_id",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "games_played_current_season",
            data_type: "integer",
            indexes: ["players_pkey"],
          },
          {
            column_name: "draft_year",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "draft_round",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "draft_number",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "greatest_75_flag",
            data_type: "boolean",
            indexes: ["players_pkey"],
          },
          {
            column_name: "from_year",
            data_type: "integer",
            indexes: ["players_pkey"],
          },
          {
            column_name: "to_year",
            data_type: "integer",
            indexes: ["players_pkey"],
          },
          {
            column_name: "college",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "country",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "birthdate",
            data_type: "date",
            indexes: ["players_pkey"],
          },
          {
            column_name: "birth_city",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "birth_state",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "birth_country",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "team_name",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "team_abbreviation",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "team_city",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "player_code",
            data_type: "text",
            indexes: ["players_pkey"],
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            indexes: ["players_pkey"],
          },
          {
            column_name: "updated_at",
            data_type: "timestamp without time zone",
            indexes: ["players_pkey"],
          },
          {
            column_name: "headshot_url",
            data_type: "text",
            indexes: ["players_pkey"],
          },
        ],
        indexes: [
          {
            name: "players_pkey",
            columns: [
              "id",
              "full_name",
              "first_name",
              "last_name",
              "is_active",
              "team_id",
              "height",
              "weight",
              "season_exp",
              "jersey",
              "position",
              "rosterstatus",
              "games_played_current_season_id",
              "games_played_current_season",
              "draft_year",
              "draft_round",
              "draft_number",
              "greatest_75_flag",
              "from_year",
              "to_year",
              "college",
              "country",
              "birthdate",
              "birth_city",
              "birth_state",
              "birth_country",
              "team_name",
              "team_abbreviation",
              "team_city",
              "player_code",
              "created_at",
              "updated_at",
              "headshot_url",
            ],
          },
        ],
      },
      {
        table_name: "team_hustle_stats",
        columns: [
          {
            column_name: "id",
            data_type: "integer",
            indexes: ["unique_team_game_hustle", "team_hustle_stats_pkey"],
            constraints: [
              {
                type: "PRIMARY KEY",
                name: "team_hustle_stats_pkey",
              },
              {
                type: "PRIMARY KEY",
                name: "team_hustle_stats_pkey",
              },
            ],
          },
          {
            column_name: "game_id",
            data_type: "character varying",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
            constraints: [
              {
                type: "UNIQUE",
                name: "unique_team_game_hustle",
              },
              {
                type: "UNIQUE",
                name: "unique_team_game_hustle",
              },
            ],
          },
          {
            column_name: "team_id",
            data_type: "integer",
            indexes: ["unique_team_game_hustle", "team_hustle_stats_pkey"],
            constraints: [
              {
                type: "UNIQUE",
                name: "unique_team_game_hustle",
              },
              {
                type: "UNIQUE",
                name: "unique_team_game_hustle",
              },
            ],
          },
          {
            column_name: "team_name",
            data_type: "text",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "team_abbreviation",
            data_type: "text",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "team_city",
            data_type: "text",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "minutes",
            data_type: "text",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "pts",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "contested_shots",
            data_type: "integer",
            indexes: ["unique_team_game_hustle", "team_hustle_stats_pkey"],
          },
          {
            column_name: "contested_shots_2pt",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "contested_shots_3pt",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "deflections",
            data_type: "integer",
            indexes: ["unique_team_game_hustle", "team_hustle_stats_pkey"],
          },
          {
            column_name: "charges_drawn",
            data_type: "integer",
            indexes: ["unique_team_game_hustle", "team_hustle_stats_pkey"],
          },
          {
            column_name: "screen_assists",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "screen_ast_pts",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "off_loose_balls_recovered",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "def_loose_balls_recovered",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "loose_balls_recovered",
            data_type: "integer",
            indexes: ["unique_team_game_hustle", "team_hustle_stats_pkey"],
          },
          {
            column_name: "off_boxouts",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "def_boxouts",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "box_out_player_team_rebs",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "box_out_player_rebs",
            data_type: "integer",
            indexes: ["team_hustle_stats_pkey", "unique_team_game_hustle"],
          },
          {
            column_name: "box_outs",
            data_type: "integer",
            indexes: ["unique_team_game_hustle", "team_hustle_stats_pkey"],
          },
          {
            column_name: "created_at",
            data_type: "timestamp without time zone",
            indexes: ["unique_team_game_hustle", "team_hustle_stats_pkey"],
          },
        ],
        indexes: [
          {
            name: "unique_team_game_hustle",
            columns: [
              "id",
              "game_id",
              "team_id",
              "team_name",
              "team_abbreviation",
              "team_city",
              "minutes",
              "pts",
              "contested_shots",
              "contested_shots_2pt",
              "contested_shots_3pt",
              "deflections",
              "charges_drawn",
              "screen_assists",
              "screen_ast_pts",
              "off_loose_balls_recovered",
              "def_loose_balls_recovered",
              "loose_balls_recovered",
              "off_boxouts",
              "def_boxouts",
              "box_out_player_team_rebs",
              "box_out_player_rebs",
              "box_outs",
              "created_at",
            ],
          },
          {
            name: "team_hustle_stats_pkey",
            columns: [
              "id",
              "game_id",
              "team_id",
              "team_name",
              "team_abbreviation",
              "team_city",
              "minutes",
              "pts",
              "contested_shots",
              "contested_shots_2pt",
              "contested_shots_3pt",
              "deflections",
              "charges_drawn",
              "screen_assists",
              "screen_ast_pts",
              "off_loose_balls_recovered",
              "def_loose_balls_recovered",
              "loose_balls_recovered",
              "off_boxouts",
              "def_boxouts",
              "box_out_player_team_rebs",
              "box_out_player_rebs",
              "box_outs",
              "created_at",
            ],
          },
        ],
      },
      {
        table_name: "teams",
        columns: [
          {
            column_name: "id",
            data_type: "integer",
            indexes: ["teams_pkey"],
            constraints: [
              {
                type: "PRIMARY KEY",
                name: "teams_pkey",
              },
            ],
          },
          {
            column_name: "full_name",
            data_type: "character varying",
            indexes: ["teams_pkey"],
          },
          {
            column_name: "abbreviation",
            data_type: "character varying",
            indexes: ["teams_pkey"],
          },
          {
            column_name: "nickname",
            data_type: "character varying",
            indexes: ["teams_pkey"],
          },
          {
            column_name: "city",
            data_type: "character varying",
            indexes: ["teams_pkey"],
          },
          {
            column_name: "state",
            data_type: "character varying",
            indexes: ["teams_pkey"],
          },
          {
            column_name: "year_founded",
            data_type: "integer",
            indexes: ["teams_pkey"],
          },
        ],
        indexes: [
          {
            name: "teams_pkey",
            columns: [
              "id",
              "full_name",
              "abbreviation",
              "nickname",
              "city",
              "state",
              "year_founded",
            ],
          },
        ],
      },
      {
        table_name: "user_prompts",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            indexes: ["user_prompts_pkey"],
            constraints: [
              {
                type: "PRIMARY KEY",
                name: "user_prompts_pkey",
              },
            ],
          },
          {
            column_name: "user_id",
            data_type: "uuid",
            indexes: ["user_prompts_pkey"],
            constraints: [
              {
                type: "FOREIGN KEY",
                name: "user_prompts_user_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
            ],
          },
          {
            column_name: "prompt",
            data_type: "text",
            indexes: ["user_prompts_pkey"],
          },
          {
            column_name: "success",
            data_type: "boolean",
            indexes: ["user_prompts_pkey"],
          },
          {
            column_name: "query",
            data_type: "text",
            indexes: ["user_prompts_pkey"],
          },
          {
            column_name: "created_at",
            data_type: "timestamp with time zone",
            indexes: ["user_prompts_pkey"],
          },
          {
            column_name: "custom_summary",
            data_type: "text",
            indexes: ["user_prompts_pkey"],
          },
        ],
        indexes: [
          {
            name: "user_prompts_pkey",
            columns: [
              "id",
              "user_id",
              "prompt",
              "success",
              "query",
              "created_at",
              "custom_summary",
            ],
          },
        ],
      },
      {
        table_name: "users",
        columns: [
          {
            column_name: "id",
            data_type: "uuid",
            indexes: [
              "users_pkey",
              "users_username_key",
              "email_change_token_current_idx",
              "users_email_partial_key",
              "users_instance_id_email_idx",
              "users_instance_id_idx",
              "users_is_anonymous_idx",
              "users_phone_key",
              "recovery_token_idx",
              "email_change_token_new_idx",
              "idx_users_username",
              "reauthentication_token_idx",
              "confirmation_token_idx",
              "idx_users_email",
            ],
            constraints: [
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "FOREIGN KEY",
                name: "users_id_fkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
              {
                type: "PRIMARY KEY",
                name: "users_pkey",
                foreign_table: "auth.users",
                foreign_column: "id",
              },
            ],
          },
          {
            column_name: "email",
            data_type: "text",
            indexes: [
              "users_phone_key",
              "email_change_token_new_idx",
              "idx_users_username",
              "reauthentication_token_idx",
              "confirmation_token_idx",
              "idx_users_email",
              "users_pkey",
              "users_username_key",
              "email_change_token_current_idx",
              "users_email_partial_key",
              "users_instance_id_email_idx",
              "users_instance_id_idx",
              "users_is_anonymous_idx",
              "recovery_token_idx",
            ],
          },
          {
            column_name: "profile_image_url",
            data_type: "text",
            indexes: [
              "users_pkey",
              "users_username_key",
              "email_change_token_current_idx",
              "users_email_partial_key",
              "users_instance_id_email_idx",
              "users_instance_id_idx",
              "users_is_anonymous_idx",
              "users_phone_key",
              "recovery_token_idx",
              "email_change_token_new_idx",
              "idx_users_username",
              "reauthentication_token_idx",
              "confirmation_token_idx",
              "idx_users_email",
            ],
          },
          {
            column_name: "created_at",
            data_type: "timestamp with time zone",
            indexes: [
              "email_change_token_new_idx",
              "users_phone_key",
              "users_is_anonymous_idx",
              "users_instance_id_idx",
              "users_instance_id_email_idx",
              "users_email_partial_key",
              "email_change_token_current_idx",
              "users_username_key",
              "users_pkey",
              "idx_users_email",
              "confirmation_token_idx",
              "reauthentication_token_idx",
              "idx_users_username",
              "recovery_token_idx",
            ],
          },
          {
            column_name: "updated_at",
            data_type: "timestamp with time zone",
            indexes: [
              "idx_users_email",
              "confirmation_token_idx",
              "reauthentication_token_idx",
              "idx_users_username",
              "email_change_token_new_idx",
              "recovery_token_idx",
              "users_phone_key",
              "users_is_anonymous_idx",
              "users_instance_id_idx",
              "users_instance_id_email_idx",
              "users_email_partial_key",
              "email_change_token_current_idx",
              "users_username_key",
              "users_pkey",
            ],
          },
          {
            column_name: "first_name",
            data_type: "text",
            indexes: [
              "confirmation_token_idx",
              "users_phone_key",
              "users_is_anonymous_idx",
              "users_instance_id_idx",
              "users_instance_id_email_idx",
              "users_email_partial_key",
              "email_change_token_current_idx",
              "users_username_key",
              "users_pkey",
              "idx_users_email",
              "recovery_token_idx",
              "reauthentication_token_idx",
              "idx_users_username",
              "email_change_token_new_idx",
            ],
          },
          {
            column_name: "last_name",
            data_type: "text",
            indexes: [
              "idx_users_email",
              "confirmation_token_idx",
              "reauthentication_token_idx",
              "idx_users_username",
              "email_change_token_new_idx",
              "recovery_token_idx",
              "users_phone_key",
              "users_is_anonymous_idx",
              "users_instance_id_idx",
              "users_instance_id_email_idx",
              "users_email_partial_key",
              "email_change_token_current_idx",
              "users_username_key",
              "users_pkey",
            ],
          },
          {
            column_name: "username",
            data_type: "text",
            indexes: [
              "users_pkey",
              "users_username_key",
              "email_change_token_current_idx",
              "users_email_partial_key",
              "users_instance_id_email_idx",
              "users_instance_id_idx",
              "users_is_anonymous_idx",
              "users_phone_key",
              "recovery_token_idx",
              "email_change_token_new_idx",
              "idx_users_username",
              "reauthentication_token_idx",
              "confirmation_token_idx",
              "idx_users_email",
            ],
            constraints: [
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
              {
                type: "UNIQUE",
                name: "users_username_key",
              },
            ],
          },
        ],
        indexes: [
          {
            name: "users_pkey",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "users_username_key",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "email_change_token_current_idx",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "users_email_partial_key",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "users_instance_id_email_idx",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "users_instance_id_idx",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "users_is_anonymous_idx",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "users_phone_key",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "recovery_token_idx",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "email_change_token_new_idx",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "idx_users_username",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "reauthentication_token_idx",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "confirmation_token_idx",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
          {
            name: "idx_users_email",
            columns: [
              "id",
              "email",
              "profile_image_url",
              "created_at",
              "updated_at",
              "first_name",
              "last_name",
              "username",
            ],
          },
        ],
      },
    ],
  },
]`;

export default schema;
